#! /bin/sh

maybe_e=`ifconfig | grep -o '^e.*:' | head -n1 | cut -d: -f 1`
maybe_w=`ifconfig | grep -o '^w.*:' | head -n1 | cut -d: -f 1`

eth0=$maybe_e
wlan0=$maybe_w

cat << EOF
general {
        colors = true
        interval = 5
}

order += "ipv6"
order += "disk /"
order += "wireless $wlan0"
order += "ethernet $eth0"
order += "battery 1"
order += "load"
order += "time"

wireless $wlan0 {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

ethernet $eth0 {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

battery 1 {
        format = "%status %percentage %remaining"
}

time {
	format = "%Y-%m-%d %H:%M:%S"
}

load {
	format = "%1min"
}

disk "/" {
	format = "%free"
}
EOF
