#! /bin/sh

net_devs=`ls /sys/class/net`
maybe_e=`echo "$net_devs" | grep '^e' | head -n1`
maybe_w=`echo "$net_devs" | grep '^w' | head -n1`

#maybe_e=`ifconfig -a | grep -o '^e.*:' | head -n1 | cut -d: -f 1 | cut -d' ' -f1`
#maybe_w=`ifconfig -a | grep -o '^w.*:' | head -n1 | cut -d: -f 1 | cut -d' ' -f1`

eth0=$maybe_e
wlan0=$maybe_w

battery_num=""
for b in /sys/class/power_supply/BAT*; do
	if [ -e "$b" ]; then
		battery_num="$(basename "$b")"
		battery_num="${battery_num##BAT}"
		break
	fi
done

cat << EOF
general {
        colors = true
        interval = 5
}

order += "ipv6"
order += "disk /"
order += "volume master"
EOF

if [ -n "$wlan0" ]; then
cat << EOF
order += "wireless $wlan0"
wireless $wlan0 {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}
EOF
fi

cat << EOF
order += "ethernet $eth0"
EOF


if [ -n "$battery_num" ]; then
cat << EOF
order += "battery $battery_num"
battery $battery_num {
        format = "%status %percentage %remaining"
}
EOF
fi

cat << EOF
order += "load"
order += "time"

volume master {
        format = "♪: %volume"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

ethernet $eth0 {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

time {
	format = "%Y-%m-%d %H:%M:%S"
}

load {
	format = "%1min"
}

disk "/" {
	format = "%free"
}
EOF

if [ -n "$wlan0" ]; then
cat << EOF
wireless $wlan0 {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}
EOF
fi
